In [3]:
import numpy as np
import tensorflow as tf

/home/yan/anaconda3/envs/tf_gpu_env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/yan/anaconda3/envs/tf_gpu_env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/yan/anaconda3/envs/tf_gpu_env/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/yan/anaconda3/envs/tf_gpu_env/lib/pyt

In [4]:
x = np.random.randn(2,4,5)
x[1, 1:] = 0
seq_lengths = [4,1]
print('x:\n',x)

x:
 [[[ 1.15975542  1.02436515 -0.43608262  0.18939116  1.93666151]
  [-0.94947125 -0.69520726 -0.43701451 -0.41885374 -0.01509841]
  [ 0.59137025 -0.46877241 -1.00614372  0.74666848  0.65863591]
  [ 0.88245305  0.00665307 -0.08108788  0.53271626 -0.2211278 ]]

 [[-0.45043179 -1.18983005  0.73417743  1.14901042 -0.24557642]
  [ 0.          0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.          0.        ]]]


In [10]:
cell = tf.contrib.rnn.BasicLSTMCell(num_units=5, state_is_tuple=True, reuse=True)
outputs, last_states = tf.nn.dynamic_rnn(cell, x, seq_lengths, dtype=tf.float64)

ValueError: Trying to share variable rnn/basic_lstm_cell/kernel, but specified shape (10, 20) and found shape (8, 12).