In [11]:
import tensorflow as tf
import numpy as np
a = np.array([[2,0,0,0,0,0,0,0],
             [0,0,0,0,1,0,0,0],
             [0,0,0,0,1,0,0,0]])
print(a)
# tensor_a = tf.convert_to_tensor(a)
# print(tensor_a)
# print(tf.math.argmax(a,1))
# b = tf.constant(a)
# print(tf.argmax(b,1))
sess = tf.Session()
b = sess.run(tf.argmax(a,1))
print(b)

[[2 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0]]
[0 4 4]
